# Generated by Django 5.2.8 on 2026-01-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default=None, max_length=700),
        ),
    ]
